server:
  port: 8889

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: ${java7configurl}
          default-label: main
          skip-ssl-validation: true
          username: ${java7configusername}
          password: ${java7configpassword}