server:
  port: 8085

spring:
  #sunucu olarak kullanılacak mail burda yazılmalıdır. Yani kayıt olurken girilen mail'e aktivasyon kodu gönderecek
  #ana mail burada yazılır.
  mail:
    username: ${mailUsername}
    password: ${mailPassword}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: mail-service
  rabbitmq:
    host: localhost
    port: 5672
    username: java7
    password: root


rabbitmq:
  registerMailQueue: mail-queue


